# 02-userconfig.conf
# block hosts from Malaysia
# deny 110.159.0.0/16;
# deny 175.136.0.0/16;
# deny 175.137.0.0/16;
# deny 175.138.0.0/16;
# deny 175.139.0.0/16;
# deny 175.140.0.0/16;
# deny 175.141.0.0/16;
# deny 175.142.0.0/16;
# deny 175.143.0.0/16;

set_real_ip_from 10.0.0.0/8;
set_real_ip_from 172.16.0.0/16;
set_real_ip_from 172.17.0.0/16;
set_real_ip_from 172.18.0.0/16;
set_real_ip_from 172.19.0.0/16;
set_real_ip_from 172.20.0.0/16;
set_real_ip_from 172.21.0.0/16;
set_real_ip_from 172.22.0.0/16;
set_real_ip_from 172.23.0.0/16;
set_real_ip_from 172.24.0.0/16;
set_real_ip_from 172.25.0.0/16;
set_real_ip_from 172.26.0.0/16;
set_real_ip_from 172.27.0.0/16;
set_real_ip_from 172.28.0.0/16;
set_real_ip_from 172.29.0.0/16;
set_real_ip_from 172.30.0.0/16;
set_real_ip_from 172.31.0.0/16;
set_real_ip_from 192.168.0.0/24;
real_ip_header X-Forwarded-For;

# allow access from localhost
allow 127.0.0.1;
allow ::1;

allow 10.0.0.0/8;

# Add trailing slash to */wp-admin requests.
rewrite /wp-admin$ $scheme://$host$uri/ permanent;

# Set a variable to work around the lack of nested conditionals
set $cache_uri $request_uri;

# POST requests and urls with a query string should always go to PHP
if ($request_method = POST) {
    set $cache_uri 'no cache';
}
if ($query_string != "") {
    set $cache_uri 'no cache';
}

# Don't cache uris containing the following segments
if ($request_uri ~* "(\/wp-admin\/|\/xmlrpc.php|\/wp-(app|cron|login|register|mail)\.php|wp-.*\.php|index\.php|wp\-comments\-popup\.php|wp\-links\-opml\.php|wp\-locations\.php)") {
    set $cache_uri "no cache";
}

# Don't use the cache for logged in users or recent commenters
if ($http_cookie ~* "comment_author|wordpress_[a-f0-9]+|wp\-postpass|wordpress_logged_in") {
    set $cache_uri 'no cache';
}

# Cache static files for as long as possible
location ~* \.(xml|ogg|ogv|svg|svgz|eot|otf|woff|mp4|ttf|css|rss|atom|js|jpg|jpeg|gif|png|ico|zip|tgz|gz|rar|bz2|doc|xls|exe|ppt|tar|mid|midi|wav|bmp|rtf)$ {
    try_files       $uri =404;
    expires         max;
    access_log      off;
}

rewrite ^/sitemap(-+([a-zA-Z0-9_-]+))?\.xml$ "/index.php?xml_sitemap=params=$2" last;
rewrite ^/sitemap(-+([a-zA-Z0-9_-]+))?\.xml\.gz$ "/index.php?xml_sitemap=params=$2;zip=true" last;
rewrite ^/sitemap(-+([a-zA-Z0-9_-]+))?\.html$ "/index.php?xml_sitemap=params=$2;html=true" last;
rewrite ^/sitemap(-+([a-zA-Z0-9_-]+))?\.html.gz$ "/index.php?xml_sitemap=params=$2;html=true;zip=true" last;

if ($http_referer ~* (viagra|cialis|levitra) ) {
   return 403;
}

# healthz
location = /healthz.php {
    # check user-agent:
    if ($http_user_agent !~ ^kube-probe/) {
        return 403;
    }
    access_log off;
    try_files $uri /healthz.php$is_args$args;
}

# Deny all attempts to access hidden files such as .htaccess, .htpasswd, .DS_Store (Mac).
location ~ /\. {
    return 403;
}

# Deny all attempts to nginx configuration files.
location ~ \.(conf) {
    return 403;
}

# Deny access to any files with a .php extension in the uploads directory
location ~* ^/wp-content/uploads/.*.php$ {
    return 403;
}

# Deny all attempts to wordpress configuration files.
location ~ /wp-config.php$ {
    return 403;
}

location ~ /wp-config-sample.php$ {
    return 403;
}

# Disable XML-RPC
location ^~ /xmlrpc.php {
    # Allow Jetpack IPs to pass
    # allow 192.0.64.0/18;
    # allow 64.34.206.0/24;
    # allow 198.181.116.0/22;
    # allow 66.155.105.128/26;
    # allow 69.90.253.0/24;
    # allow 76.74.248.128/25;
    # allow 76.74.255.0/25;
    # allow 2001:1978:1e00:3::/64;
    # allow 2620:115:c000::/40;
    # deny all;
    return 418;
}

location ^~ /readme.html {
    return 403;
}

location ^~ /license.txt {
    return 403;
}

include /var/www/html/nginx*.conf;

