{{- /*
Copyright IO ANALYTICA. All Rights Reserved.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.memcached.enabled }}
{{- if and .Values.memcached.persistence.enabled (not .Values.memcached.persistence.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.names.fullname" . }}-cache-data
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.memcached.persistence.storageClass }}
  storageClassName: {{ .Values.memcached.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.memcached.persistence.size }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-cache
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "common.names.name" . }}-cache
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: redis
    - name: memcached
      protocol: TCP
      port: 11211
      targetPort: memcached
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-cache
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "common.names.name" . }}-cache
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "common.names.name" . }}-cache
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: dragonfly
          image: {{ .Values.memcached.image }}
          command:
            - dragonfly
            - --requirepass=$(DFLY_PASSWORD)
            - --memcached_port=11211
          env:
            - name: DFLY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "wordpress.secretName" . }}
                  key: cache-password
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
            - name: memcached
              containerPort: 11211
              protocol: TCP
          volumeMounts:
            - name: cache-data
              mountPath: /data
          {{- with .Values.memcached.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: cache-data
          {{- if .Values.memcached.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.memcached.persistence.existingClaim | default (printf "%s-cache-data" (include "common.names.fullname" .)) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
