{{- if and .Values.idx.enabled .Values.idx.reindexApiKey (not .Values.idx.existingReindexApiKeySecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-idx" (include "common.names.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
type: Opaque
data:
  idx-reindex-api-key: {{ .Values.idx.reindexApiKey | b64enc | quote }}
{{- end }}
