#!/usr/bin/env sh

mkdir -p "$APP_PATH"/wp-content
chown www-data:www-data "$APP_PATH"/wp-content

if [ -z "$(ls -A "$APP_PATH"/wp-content)" ]; then
    debug-echo -i "Installing Wordpress into $APP_PATH …"
    tar --strip-components=1 -C /var/www/html -xzf /home/www-data/wordpress.tgz
    chown -R www-data:www-data /var/www/html/wp-content
else
    debug-echo -i "Updating Wordpress in $APP_PATH …"
    tar --strip-components=1 -C /var/www/html --exclude=wordpress/wp-content -xzf /home/www-data/wordpress.tgz
fi

chown www-data:www-data /var/www/html/*
chown -R www-data:www-data /var/www/html/wp-includes
chown -R www-data:www-data /var/www/html/wp-admin

debug-echo -s "Wordpress $(wp core version) is available in $APP_PATH."

