#!/usr/bin/env sh

debug-echo -i "Installing Wordpress to $APP_PATH …"
tar --strip-components=1 -C /var/www/html --exclude=wordpress/wp-content -xzf /home/www-data/wordpress.tgz

mkdir -p "$APP_PATH"/wp-content
chown www-data:www-data "$APP_PATH"/wp-content

if [ -z "$(ls -A "$APP_PATH"/wp-content)" ]; then

    debug-echo -i "Installing Wordpress wp_content to $APP_PATH …"
    tar --strip-components=1 -C /var/www/html -xzf /home/www-data/wordpress.tgz
    chown -R www-data:www-data /var/www/html/wp-content

fi

chown www-data:www-data /var/www/html/*
chown -R www-data:www-data /var/www/html/wp-includes
chown -R www-data:www-data /var/www/html/wp-admin

debug-echo -s "Wordpress $(wp core version) is available in $APP_PATH."

    # wp core install \
    #     --url=${WORDPRESS_URL:-localhost} \
    #     --title=${WORDPRESS_TITLE:-New Website} \
    #     --admin_user=${WORDPRESS_ADMIN_USER:-admin} \
    #     --admin_password=${WORDPRESS_ADMIN_PASSWORD:-admin} \
    #     --admin_email=${WORDPRESS_ADMIN_EMAIL:-admin@localhost} \
    #     --skip-email --quiet

